system.debug('Merhaba');
system.debug('hava guzel');


string city;   //deklare
system.debug(city);
string country = '';  // bos degerler
system.debug(country);
string region ='America';
system.debug(region);

string sehir = 'istanbul';
string text = 'Turkiye\'nin en kalabalık sehri ' + sehir;
system.debug(text);

integer sayi1 = 50;
system.debug(sayi1);
integer sayi2 = 50/2;
system.debug(sayi2);

boolean isActive = true;
system.debug(isActive);

Boolean cond1 = 5>3;
System.debug('5>3 mu? => ' + cond1);
Boolean cond2 = 11>100;
System.debug('11>100 mu? => ' + cond2);



