Calculator c = new Calculator();
system.debug(c.dynamicCalulationMethod(30, 30.60, 'Addition'));
system.debug(c.dynamicCalulationMethod(90, 60, 'Substraction'));
system.debug(c.dynamicCalulationMethod(8, 2, 'Division'));
system.debug(c.dynamicCalulationMethod(6, 4, 'Multiplication'));

Calculator.calculatorDiscount(1000);
Calculator.calculatorDiscount(800);
Calculator.calculatorDiscount(200);
Calculator.calculatorDiscount(100);

Calculator.calculateNetPrice(1000, 3.5);